"""
K24 Intent Classification - Intent Definitions
===============================================
Comprehensive list of 60+ accounting intents across 8 categories.
"""

from enum import Enum
from typing import Dict, List

class IntentCategory(str, Enum):
    """Intent categories for K24 accounting system"""
    READ_QUERIES = "READ_QUERIES"
    CREATE_OPERATIONS = "CREATE_OPERATIONS"
    UPDATE_OPERATIONS = "UPDATE_OPERATIONS"
    DELETE_OPERATIONS = "DELETE_OPERATIONS"
    COMPLIANCE_QUERIES = "COMPLIANCE_QUERIES"
    ANALYTICS = "ANALYTICS"
    META_OPERATIONS = "META_OPERATIONS"
    FALLBACK = "FALLBACK"

class Intent(str, Enum):
    """All 68 intents supported by K24"""
    
    # READ_QUERIES (15 intents)
    QUERY_OUTSTANDING_INVOICES = "QUERY_OUTSTANDING_INVOICES"
    QUERY_CASH_POSITION = "QUERY_CASH_POSITION"
    QUERY_CUSTOMER_BALANCE = "QUERY_CUSTOMER_BALANCE"
    QUERY_GST_LIABILITY = "QUERY_GST_LIABILITY"
    QUERY_TDS_OBLIGATION = "QUERY_TDS_OBLIGATION"
    QUERY_SALES_REPORT = "QUERY_SALES_REPORT"
    QUERY_EXPENSE_REPORT = "QUERY_EXPENSE_REPORT"
    QUERY_PROFIT_LOSS = "QUERY_PROFIT_LOSS"
    QUERY_AGED_RECEIVABLES = "QUERY_AGED_RECEIVABLES"
    QUERY_AGED_PAYABLES = "QUERY_AGED_PAYABLES"
    QUERY_INVENTORY_STATUS = "QUERY_INVENTORY_STATUS"
    QUERY_CUSTOMER_CREDIT_LIMIT = "QUERY_CUSTOMER_CREDIT_LIMIT"
    QUERY_VENDOR_PAYMENT_TERMS = "QUERY_VENDOR_PAYMENT_TERMS"
    QUERY_BANK_RECONCILIATION = "QUERY_BANK_RECONCILIATION"
    QUERY_FINANCIAL_RATIO = "QUERY_FINANCIAL_RATIO"
    
    # CREATE_OPERATIONS (12 intents)
    CREATE_INVOICE = "CREATE_INVOICE"
    CREATE_RECEIPT = "CREATE_RECEIPT"
    CREATE_PAYMENT = "CREATE_PAYMENT"
    CREATE_CREDIT_NOTE = "CREATE_CREDIT_NOTE"
    CREATE_DEBIT_NOTE = "CREATE_DEBIT_NOTE"
    CREATE_JOURNAL_ENTRY = "CREATE_JOURNAL_ENTRY"
    CREATE_CUSTOMER = "CREATE_CUSTOMER"
    CREATE_VENDOR = "CREATE_VENDOR"
    CREATE_EXPENSE_ENTRY = "CREATE_EXPENSE_ENTRY"
    CREATE_BANK_DEPOSIT = "CREATE_BANK_DEPOSIT"
    CREATE_BANK_WITHDRAWAL = "CREATE_BANK_WITHDRAWAL"
    CREATE_INVENTORY_ENTRY = "CREATE_INVENTORY_ENTRY"
    
    # UPDATE_OPERATIONS (10 intents)
    UPDATE_INVOICE_AMOUNT = "UPDATE_INVOICE_AMOUNT"
    UPDATE_INVOICE_DATE = "UPDATE_INVOICE_DATE"
    UPDATE_CUSTOMER_DETAILS = "UPDATE_CUSTOMER_DETAILS"
    UPDATE_VENDOR_DETAILS = "UPDATE_VENDOR_DETAILS"
    UPDATE_LEDGER_NAME = "UPDATE_LEDGER_NAME"
    UPDATE_PAYMENT_STATUS = "UPDATE_PAYMENT_STATUS"
    UPDATE_INVENTORY_QUANTITY = "UPDATE_INVENTORY_QUANTITY"
    UPDATE_GST_RATE = "UPDATE_GST_RATE"
    UPDATE_BANK_RECONCILIATION = "UPDATE_BANK_RECONCILIATION"
    UPDATE_CREDIT_LIMIT = "UPDATE_CREDIT_LIMIT"
    
    # DELETE_OPERATIONS (8 intents)
    DELETE_INVOICE = "DELETE_INVOICE"
    DELETE_RECEIPT = "DELETE_RECEIPT"
    DELETE_PAYMENT = "DELETE_PAYMENT"
    DELETE_JOURNAL_ENTRY = "DELETE_JOURNAL_ENTRY"
    DELETE_CUSTOMER_DRAFT = "DELETE_CUSTOMER_DRAFT"
    DELETE_VENDOR_DRAFT = "DELETE_VENDOR_DRAFT"
    DELETE_INVENTORY_ENTRY = "DELETE_INVENTORY_ENTRY"
    DELETE_EXPENSE_ENTRY = "DELETE_EXPENSE_ENTRY"
    
    # COMPLIANCE_QUERIES (10 intents)
    QUERY_GST_FILING_DEADLINE = "QUERY_GST_FILING_DEADLINE"
    QUERY_TDS_FILING_DEADLINE = "QUERY_TDS_FILING_DEADLINE"
    QUERY_ITR_FILING_DEADLINE = "QUERY_ITR_FILING_DEADLINE"
    QUERY_AUDIT_REQUIREMENTS = "QUERY_AUDIT_REQUIREMENTS"
    QUERY_COMPLIANCE_STATUS = "QUERY_COMPLIANCE_STATUS"
    QUERY_TAX_CALENDAR = "QUERY_TAX_CALENDAR"
    QUERY_REGULATORY_REQUIREMENTS = "QUERY_REGULATORY_REQUIREMENTS"
    QUERY_GSTR1_STATUS = "QUERY_GSTR1_STATUS"
    QUERY_GSTR3B_STATUS = "QUERY_GSTR3B_STATUS"
    QUERY_ITC_ELIGIBILITY = "QUERY_ITC_ELIGIBILITY"
    
    # ANALYTICS (8 intents)
    ANALYTICS_SALES_TREND = "ANALYTICS_SALES_TREND"
    ANALYTICS_EXPENSE_TREND = "ANALYTICS_EXPENSE_TREND"
    ANALYTICS_PROFIT_TREND = "ANALYTICS_PROFIT_TREND"
    ANALYTICS_CUSTOMER_CHURN = "ANALYTICS_CUSTOMER_CHURN"
    ANALYTICS_TOP_CUSTOMERS = "ANALYTICS_TOP_CUSTOMERS"
    ANALYTICS_PAYMENT_DELAYS = "ANALYTICS_PAYMENT_DELAYS"
    ANALYTICS_CASH_FLOW_FORECAST = "ANALYTICS_CASH_FLOW_FORECAST"
    ANALYTICS_GROSS_MARGIN_TREND = "ANALYTICS_GROSS_MARGIN_TREND"
    
    # META_OPERATIONS (5 intents)
    HELP_REQUEST = "HELP_REQUEST"
    FEEDBACK_SUGGESTION = "FEEDBACK_SUGGESTION"
    REPORT_BUG = "REPORT_BUG"
    REQUEST_FEATURE = "REQUEST_FEATURE"
    EXPORT_DATA = "EXPORT_DATA"
    
    # FALLBACK (2 intents)
    CLARIFY_REQUEST = "CLARIFY_REQUEST"
    UNKNOWN = "UNKNOWN"

# Intent to category mapping
INTENT_TO_CATEGORY: Dict[str, IntentCategory] = {
    # READ_QUERIES
    Intent.QUERY_OUTSTANDING_INVOICES: IntentCategory.READ_QUERIES,
    Intent.QUERY_CASH_POSITION: IntentCategory.READ_QUERIES,
    Intent.QUERY_CUSTOMER_BALANCE: IntentCategory.READ_QUERIES,
    Intent.QUERY_GST_LIABILITY: IntentCategory.READ_QUERIES,
    Intent.QUERY_TDS_OBLIGATION: IntentCategory.READ_QUERIES,
    Intent.QUERY_SALES_REPORT: IntentCategory.READ_QUERIES,
    Intent.QUERY_EXPENSE_REPORT: IntentCategory.READ_QUERIES,
    Intent.QUERY_PROFIT_LOSS: IntentCategory.READ_QUERIES,
    Intent.QUERY_AGED_RECEIVABLES: IntentCategory.READ_QUERIES,
    Intent.QUERY_AGED_PAYABLES: IntentCategory.READ_QUERIES,
    Intent.QUERY_INVENTORY_STATUS: IntentCategory.READ_QUERIES,
    Intent.QUERY_CUSTOMER_CREDIT_LIMIT: IntentCategory.READ_QUERIES,
    Intent.QUERY_VENDOR_PAYMENT_TERMS: IntentCategory.READ_QUERIES,
    Intent.QUERY_BANK_RECONCILIATION: IntentCategory.READ_QUERIES,
    Intent.QUERY_FINANCIAL_RATIO: IntentCategory.READ_QUERIES,
    
    # CREATE_OPERATIONS
    Intent.CREATE_INVOICE: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_RECEIPT: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_PAYMENT: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_CREDIT_NOTE: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_DEBIT_NOTE: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_JOURNAL_ENTRY: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_CUSTOMER: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_VENDOR: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_EXPENSE_ENTRY: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_BANK_DEPOSIT: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_BANK_WITHDRAWAL: IntentCategory.CREATE_OPERATIONS,
    Intent.CREATE_INVENTORY_ENTRY: IntentCategory.CREATE_OPERATIONS,
    
    # UPDATE_OPERATIONS
    Intent.UPDATE_INVOICE_AMOUNT: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_INVOICE_DATE: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_CUSTOMER_DETAILS: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_VENDOR_DETAILS: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_LEDGER_NAME: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_PAYMENT_STATUS: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_INVENTORY_QUANTITY: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_GST_RATE: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_BANK_RECONCILIATION: IntentCategory.UPDATE_OPERATIONS,
    Intent.UPDATE_CREDIT_LIMIT: IntentCategory.UPDATE_OPERATIONS,
    
    # DELETE_OPERATIONS
    Intent.DELETE_INVOICE: IntentCategory.DELETE_OPERATIONS,
    Intent.DELETE_RECEIPT: IntentCategory.DELETE_OPERATIONS,
    Intent.DELETE_PAYMENT: IntentCategory.DELETE_OPERATIONS,
    Intent.DELETE_JOURNAL_ENTRY: IntentCategory.DELETE_OPERATIONS,
    Intent.DELETE_CUSTOMER_DRAFT: IntentCategory.DELETE_OPERATIONS,
    Intent.DELETE_VENDOR_DRAFT: IntentCategory.DELETE_OPERATIONS,
    Intent.DELETE_INVENTORY_ENTRY: IntentCategory.DELETE_OPERATIONS,
    Intent.DELETE_EXPENSE_ENTRY: IntentCategory.DELETE_OPERATIONS,
    
    # COMPLIANCE_QUERIES
    Intent.QUERY_GST_FILING_DEADLINE: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_TDS_FILING_DEADLINE: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_ITR_FILING_DEADLINE: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_AUDIT_REQUIREMENTS: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_COMPLIANCE_STATUS: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_TAX_CALENDAR: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_REGULATORY_REQUIREMENTS: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_GSTR1_STATUS: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_GSTR3B_STATUS: IntentCategory.COMPLIANCE_QUERIES,
    Intent.QUERY_ITC_ELIGIBILITY: IntentCategory.COMPLIANCE_QUERIES,
    
    # ANALYTICS
    Intent.ANALYTICS_SALES_TREND: IntentCategory.ANALYTICS,
    Intent.ANALYTICS_EXPENSE_TREND: IntentCategory.ANALYTICS,
    Intent.ANALYTICS_PROFIT_TREND: IntentCategory.ANALYTICS,
    Intent.ANALYTICS_CUSTOMER_CHURN: IntentCategory.ANALYTICS,
    Intent.ANALYTICS_TOP_CUSTOMERS: IntentCategory.ANALYTICS,
    Intent.ANALYTICS_PAYMENT_DELAYS: IntentCategory.ANALYTICS,
    Intent.ANALYTICS_CASH_FLOW_FORECAST: IntentCategory.ANALYTICS,
    Intent.ANALYTICS_GROSS_MARGIN_TREND: IntentCategory.ANALYTICS,
    
    # META_OPERATIONS
    Intent.HELP_REQUEST: IntentCategory.META_OPERATIONS,
    Intent.FEEDBACK_SUGGESTION: IntentCategory.META_OPERATIONS,
    Intent.REPORT_BUG: IntentCategory.META_OPERATIONS,
    Intent.REQUEST_FEATURE: IntentCategory.META_OPERATIONS,
    Intent.EXPORT_DATA: IntentCategory.META_OPERATIONS,
    
    # FALLBACK
    Intent.CLARIFY_REQUEST: IntentCategory.FALLBACK,
    Intent.UNKNOWN: IntentCategory.FALLBACK,
}

# Intent descriptions
INTENT_DESCRIPTIONS: Dict[str, str] = {
    # READ_QUERIES
    Intent.QUERY_OUTSTANDING_INVOICES: "Show unpaid/pending invoices",
    Intent.QUERY_CASH_POSITION: "Check current cash/bank balance",
    Intent.QUERY_CUSTOMER_BALANCE: "Check amount owed by specific customer",
    Intent.QUERY_GST_LIABILITY: "Check GST tax liability",
    Intent.QUERY_TDS_OBLIGATION: "Check TDS obligations",
    Intent.QUERY_SALES_REPORT: "Generate sales report",
    Intent.QUERY_EXPENSE_REPORT: "Generate expense report",
    Intent.QUERY_PROFIT_LOSS: "Show profit & loss statement",
    Intent.QUERY_AGED_RECEIVABLES: "Show receivables by age",
    Intent.QUERY_AGED_PAYABLES: "Show payables by age",
    Intent.QUERY_INVENTORY_STATUS: "Check inventory/stock levels",
    Intent.QUERY_CUSTOMER_CREDIT_LIMIT: "Check customer credit limit",
    Intent.QUERY_VENDOR_PAYMENT_TERMS: "Check vendor payment terms",
    Intent.QUERY_BANK_RECONCILIATION: "Check bank reconciliation status",
    Intent.QUERY_FINANCIAL_RATIO: "Calculate financial ratios",
    
    # CREATE_OPERATIONS
    Intent.CREATE_INVOICE: "Create a new sales invoice",
    Intent.CREATE_RECEIPT: "Record payment received",
    Intent.CREATE_PAYMENT: "Record payment made",
    Intent.CREATE_CREDIT_NOTE: "Create credit note",
    Intent.CREATE_DEBIT_NOTE: "Create debit note",
    Intent.CREATE_JOURNAL_ENTRY: "Create journal entry",
    Intent.CREATE_CUSTOMER: "Add new customer",
    Intent.CREATE_VENDOR: "Add new vendor",
    Intent.CREATE_EXPENSE_ENTRY: "Record expense",
    Intent.CREATE_BANK_DEPOSIT: "Record bank deposit",
    Intent.CREATE_BANK_WITHDRAWAL: "Record bank withdrawal",
    Intent.CREATE_INVENTORY_ENTRY: "Add inventory item",
    
    # ... (continuing for all intents)
    Intent.CLARIFY_REQUEST: "User intent unclear, needs clarification",
    Intent.UNKNOWN: "Intent cannot be determined",
}
