"use client";

import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, CheckCircle, ShieldAlert, FileText, RefreshCw, ArrowLeft, Download } from "lucide-react";
import { useRouter } from "next/navigation";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface AuditIssue {
    type: string;
    severity: "Critical" | "High" | "Medium" | "Low";
    message: string;
    details: string;
}

interface AuditReport {
    status: string;
    score: number;
    issue_count: number;
    issues: AuditIssue[];
}

export default function AuditPage() {
    const router = useRouter();
    const [report, setReport] = useState<AuditReport | null>(null);
    const [loading, setLoading] = useState(true);

    const fetchAudit = async () => {
        setLoading(true);
        try {
            const res = await fetch("http://localhost:8001/audit/run", {
                headers: { "x-api-key": "k24-secret-key-123" }
            });
            const data = await res.json();
            setReport(data);
        } catch (error) {
            console.error("Audit failed", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchAudit();
    }, []);

    const handleExportPDF = () => {
        if (!report) return;

        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.text("KITTU AI Audit Report", 14, 22);

        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);

        // Scorecard
        doc.setDrawColor(200, 200, 200);
        doc.setFillColor(250, 250, 250);
        doc.rect(14, 35, 182, 30, "FD");

        doc.setFontSize(12);
        doc.text("Overall Health Score", 20, 45);
        doc.setFontSize(24);
        doc.setTextColor(report.score > 80 ? 0 : 200, report.score > 80 ? 150 : 0, 0); // Green or Red
        doc.text(`${report.score}/100`, 20, 58);
        doc.setTextColor(0, 0, 0); // Reset

        doc.setFontSize(12);
        doc.text(`Status: ${report.status.toUpperCase()}`, 100, 45);
        doc.text(`Issues Found: ${report.issue_count}`, 100, 55);

        // Issues Table
        const tableData = report.issues.map(issue => [
            issue.severity,
            issue.type,
            issue.message,
            issue.details
        ]);

        autoTable(doc, {
            startY: 75,
            head: [['Severity', 'Type', 'Issue', 'Details']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [41, 128, 185] },
            styles: { fontSize: 10 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 25 }, // Severity
                1: { cellWidth: 30 }, // Type
                2: { cellWidth: 60 }, // Message
                3: { cellWidth: 'auto' } // Details
            },
            didParseCell: function (data) {
                if (data.section === 'body' && data.column.index === 0) {
                    const severity = data.cell.raw;
                    if (severity === 'Critical') data.cell.styles.textColor = [220, 53, 69];
                    if (severity === 'High') data.cell.styles.textColor = [253, 126, 20];
                }
            }
        });

        // Footer
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text('Confidential - Generated by KITTU Executive AI', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
        }

        doc.save(`Audit_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    const getSeverityColor = (severity: string) => {
        switch (severity) {
            case "Critical": return "bg-red-100 text-red-800 border-red-200";
            case "High": return "bg-orange-100 text-orange-800 border-orange-200";
            case "Medium": return "bg-yellow-100 text-yellow-800 border-yellow-200";
            default: return "bg-blue-100 text-blue-800 border-blue-200";
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 p-8">
            <div className="max-w-5xl mx-auto space-y-8">
                {/* Header */}
                <div className="flex justify-between items-center">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" size="icon" onClick={() => router.back()}>
                            <ArrowLeft className="h-5 w-5" />
                        </Button>
                        <div>
                            <h1 className="text-3xl font-bold tracking-tight">AI Auditor</h1>
                            <p className="text-muted-foreground">Continuous Compliance & Health Check</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" onClick={handleExportPDF} disabled={!report}>
                            <Download className="mr-2 h-4 w-4" />
                            Export PDF
                        </Button>
                        <Button onClick={fetchAudit} disabled={loading}>
                            <RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
                            Run Audit
                        </Button>
                    </div>
                </div>

                {/* Scorecard */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <Card className="md:col-span-1 bg-white border-l-4 border-l-blue-600">
                        <CardHeader>
                            <CardTitle className="text-sm font-medium text-muted-foreground">Audit Score</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-baseline gap-2">
                                <span className={`text-5xl font-bold ${(report?.score || 0) > 80 ? 'text-green-600' :
                                    (report?.score || 0) > 50 ? 'text-yellow-600' : 'text-red-600'
                                    }`}>
                                    {report?.score ?? "--"}
                                </span>
                                <span className="text-muted-foreground">/ 100</span>
                            </div>
                            <p className="text-sm mt-2 text-muted-foreground">
                                {(report?.score || 0) > 80 ? "Excellent Health" : "Needs Attention"}
                            </p>
                        </CardContent>
                    </Card>

                    <Card className="md:col-span-1">
                        <CardHeader>
                            <CardTitle className="text-sm font-medium text-muted-foreground">Issues Found</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="text-4xl font-bold text-gray-900">{report?.issue_count ?? 0}</div>
                            <p className="text-sm mt-2 text-muted-foreground">Across {report?.issues.length ? new Set(report.issues.map(i => i.type)).size : 0} categories</p>
                        </CardContent>
                    </Card>

                    <Card className="md:col-span-1">
                        <CardHeader>
                            <CardTitle className="text-sm font-medium text-muted-foreground">Status</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-center gap-2">
                                {report?.status === "clean" ? (
                                    <CheckCircle className="h-8 w-8 text-green-500" />
                                ) : (
                                    <ShieldAlert className="h-8 w-8 text-orange-500" />
                                )}
                                <span className="text-xl font-semibold capitalize">
                                    {report?.status ?? "Checking..."}
                                </span>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Issues List */}
                <Card>
                    <CardHeader>
                        <CardTitle>Detailed Findings</CardTitle>
                    </CardHeader>
                    <CardContent>
                        {!report ? (
                            <div className="text-center py-12 text-muted-foreground">Loading audit data...</div>
                        ) : report.issues.length === 0 ? (
                            <div className="text-center py-12 flex flex-col items-center gap-4">
                                <CheckCircle className="h-12 w-12 text-green-500" />
                                <h3 className="text-lg font-medium">All Systems Nominal</h3>
                                <p className="text-muted-foreground">No compliance or data quality issues found.</p>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                {report.issues.map((issue, idx) => (
                                    <div key={idx} className="flex items-start justify-between p-4 border rounded-lg hover:bg-gray-50 transition-colors">
                                        <div className="flex gap-4">
                                            <div className="mt-1">
                                                <AlertTriangle className={`h-5 w-5 ${issue.severity === 'Critical' ? 'text-red-500' : 'text-yellow-500'
                                                    }`} />
                                            </div>
                                            <div>
                                                <h4 className="font-semibold text-gray-900">{issue.message}</h4>
                                                <p className="text-sm text-muted-foreground mt-1">{issue.details}</p>
                                                <div className="flex gap-2 mt-2">
                                                    <Badge variant="outline" className="text-xs">
                                                        {issue.type}
                                                    </Badge>
                                                </div>
                                            </div>
                                        </div>
                                        <Badge className={`${getSeverityColor(issue.severity)}`}>
                                            {issue.severity}
                                        </Badge>
                                    </div>
                                ))}
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
